import { Component, ComponentCategory } from "@/types";

export const categories: ComponentCategory[] = [
  {
    id: "all",
    name: "All Libraries",
    description: "View all component libraries",
    icon: "Library",
    count: 0,
  },
  {
    id: "ui",
    name: "UI Components",
    description: "Complete UI component systems",
    icon: "Layout",
    count: 0,
  },
  {
    id: "animations",
    name: "Animations",
    description: "Motion and animation libraries",
    icon: "Sparkles",
    count: 0,
  },
  {
    id: "headless",
    name: "Headless",
    description: "Unstyled, accessible components",
    icon: "Code",
    count: 0,
  },
];

export const components: Component[] = [
  {
    id: "magicui",
    name: "Magic UI",
    description: "50+ free and open-source animated components built with React, TypeScript, Tailwind CSS, and Framer Motion.",
    category: "animations",
    tags: ["React", "TypeScript", "Tailwind", "Framer Motion", "Open Source"],
    website: "https://magicui.design/",
    image: "https://api.microlink.io/?url=https://magicui.design/&screenshot=true&meta=false&embed=screenshot.url",
    featured: true,
  },
  {
    id: "cossui",
    name: "Coss UI",
    description: "Modern React component library with beautiful, accessible components for building web applications.",
    category: "ui",
    tags: ["React", "TypeScript", "Accessible", "Modern"],
    website: "https://coss.com/ui/docs",
    image: "https://api.microlink.io/?url=https://coss.com/ui/docs&screenshot=true&meta=false&embed=screenshot.url",
    featured: true,
  },
  {
    id: "zippystarter",
    name: "Zippy Starter",
    description: "Production-ready React components and templates to ship faster with modern design patterns.",
    category: "ui",
    tags: ["React", "Templates", "Production Ready", "Starter Kit"],
    website: "https://zippystarter.com/",
    image: "https://api.microlink.io/?url=https://zippystarter.com/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "nexui",
    name: "Nex UI",
    description: "Beautiful and customizable React components for modern web applications with excellent developer experience.",
    category: "ui",
    tags: ["React", "Customizable", "Modern", "DX"],
    website: "https://www.nexui.xyz/",
    image: "https://api.microlink.io/?url=https://www.nexui.xyz/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "hextaui",
    name: "Hexta UI",
    description: "Comprehensive collection of reusable React components with clean design and smooth animations.",
    category: "ui",
    tags: ["React", "Reusable", "Animations", "Clean Design"],
    website: "https://www.hextaui.com/",
    image: "https://api.microlink.io/?url=https://www.hextaui.com/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "shadcnuikit",
    name: "shadcn UI Kit",
    description: "Extended collection of shadcn/ui components with additional features and variants.",
    category: "ui",
    tags: ["React", "shadcn", "Tailwind", "Radix UI"],
    website: "https://shadcnuikit.com/",
    image: "https://api.microlink.io/?url=https://shadcnuikit.com/&screenshot=true&meta=false&embed=screenshot.url",
    featured: true,
  },
  {
    id: "gluestack",
    name: "Gluestack UI",
    description: "Universal, styled, and accessible React Native and React components for building design systems.",
    category: "headless",
    tags: ["React", "React Native", "Universal", "Accessible", "Design System"],
    website: "https://gluestack.io/",
    image: "https://api.microlink.io/?url=https://gluestack.io/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "diceui",
    name: "Dice UI",
    description: "Modern component library with dice-rolling animations and playful interactions for React applications.",
    category: "ui",
    tags: ["React", "Animations", "Interactive", "Playful"],
    website: "https://www.diceui.com/",
    image: "https://api.microlink.io/?url=https://www.diceui.com/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "tailusui",
    name: "Tailus UI",
    description: "Premium Tailwind CSS components with beautiful designs and smooth animations for modern web apps.",
    category: "ui",
    tags: ["React", "Tailwind", "Premium", "Animations"],
    website: "https://ui.tailus.io/",
    image: "https://api.microlink.io/?url=https://ui.tailus.io/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "aisdk",
    name: "AI SDK",
    description: "Vercel's AI SDK with React components for building AI-powered applications with streaming and chat interfaces.",
    category: "ui",
    tags: ["AI", "React", "Vercel", "Streaming", "Chat"],
    website: "https://ai-sdk.dev/",
    image: "https://api.microlink.io/?url=https://ai-sdk.dev/&screenshot=true&meta=false&embed=screenshot.url",
    featured: true,
  },
  {
    id: "spectrumui",
    name: "Spectrum UI",
    description: "Beautiful React component library with vibrant designs and smooth animations for modern interfaces.",
    category: "ui",
    tags: ["React", "Modern", "Animations", "Vibrant"],
    website: "https://ui.spectrumhq.in/",
    image: "https://api.microlink.io/?url=https://ui.spectrumhq.in/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "bundui",
    name: "Bund UI",
    description: "Minimal and elegant React components with focus on simplicity and performance.",
    category: "ui",
    tags: ["React", "Minimal", "Performance", "Elegant"],
    website: "https://bundui.io/",
    image: "https://api.microlink.io/?url=https://bundui.io/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "fancycomponents",
    name: "Fancy Components",
    description: "Collection of fancy, eye-catching React components with unique animations and interactions.",
    category: "animations",
    tags: ["React", "Fancy", "Animations", "Interactive", "Eye-catching"],
    website: "https://www.fancycomponents.dev/",
    image: "https://api.microlink.io/?url=https://www.fancycomponents.dev/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "smoothui",
    name: "Smooth UI",
    description: "React components with buttery-smooth animations and transitions for polished user experiences.",
    category: "animations",
    tags: ["React", "Smooth", "Animations", "Transitions", "Polished"],
    website: "https://smoothui.dev/",
    image: "https://api.microlink.io/?url=https://smoothui.dev/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "skiperui",
    name: "Skiper UI",
    description: "Fast and lightweight React component library optimized for performance and bundle size.",
    category: "ui",
    tags: ["React", "Performance", "Lightweight", "Fast"],
    website: "https://skiper-ui.com/",
    image: "https://api.microlink.io/?url=https://skiper-ui.com/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "kiboui",
    name: "Kibo UI",
    description: "Modern React component library with Japanese-inspired minimalist design principles.",
    category: "ui",
    tags: ["React", "Minimalist", "Japanese", "Modern", "Design"],
    website: "https://www.kibo-ui.com/",
    image: "https://api.microlink.io/?url=https://www.kibo-ui.com/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "baseui",
    name: "Base UI",
    description: "A React component library by Uber that implements the Base Web design system.",
    category: "ui",
    tags: ["React", "TypeScript", "Open Source"],
    website: "https://base-ui.com/",
    image: "https://api.microlink.io/?url=https://base-ui.com/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "olivierlarose",
    name: "Olivier Larose Blog",
    description: "Blog by Olivier Larose featuring tutorials and component showcases.",
    category: "ui",
    tags: ["Blog", "Tutorials", "Components"],
    website: "https://blog.olivierlarose.com/",
    image: "https://api.microlink.io/?url=https://blog.olivierlarose.com/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "flowbite",
    name: "Flowbite",
    description: "Open-source components built with Tailwind CSS featuring interactive elements and accessible design.",
    category: "ui",
    tags: ["HTML", "Tailwind CSS", "Open Source"],
    website: "https://flowbite.com/#components",
    image: "https://api.microlink.io/?url=https://flowbite.com/#components&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
  {
    id: "tremor",
    name: "Tremor",
    description: "React components for building interactive dashboards and data visualizations.",
    category: "ui",
    tags: ["React", "Charts", "Dashboard", "Visualization"],
    website: "https://www.tremor.so/",
    image: "https://api.microlink.io/?url=https://www.tremor.so/&screenshot=true&meta=false&embed=screenshot.url",
    featured: false,
  },
];

categories.forEach(category => {
  if (category.id === "all") {
    category.count = components.length;
  } else {
    category.count = components.filter(c => c.category === category.id).length;
  }
});
